/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create admin
         * @description Create a new admin with email and password, returns JWT token and admin info
         */
        post: operations["post-create-admin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Login
         * @description Login Admin or Superadmin with email and password, returns JWT token and admin info
         */
        post: operations["get-admin-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/{idORmailORadminname}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin by ID OR Mail OR adminname
         * @description Retrieve admin information by admin ID. Returns public admin data.
         */
        get: operations["get-admin-by-identifier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LOGOUT ALL
         * @description Logs out the current or admin by clearing all the cookies.
         */
        post: operations["post-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Images or PDFs
         * @description Performs OCR on one or more uploaded files (images or PDFs). Files should be provided in a multipart form with the field name 'files'.
         */
        post: operations["post-ocr-scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create User
         * @description Create a new user with email and password, returns JWT token and user info
         */
        post: operations["post-create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User Login
         * @description Login user with email and password, returns JWT token and user info
         */
        post: operations["get-user-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get your information
         * @description Retrieve user information by user ID with the token you're logged in. Returns public user data.
         */
        get: operations["get-user-details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Users
         * @description ADMIN_ONLY. Retrieves a paginated list of all users. This endpoint is restricted to admin and superadmin roles.
         */
        get: operations["get-all-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/users/sort-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Sort Options
         * @description ADMIN_ONLY. Retrieves the list of fields that the user list can be sorted by.
         */
        get: operations["get-user-sort-options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/users/{idORmailORusername}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User by ID OR Mail OR username
         * @description ADMIN_ONLY. Retrieve user information by user ID. Returns public user data.
         */
        get: operations["get-user-by-identifier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get healthz */
        get: operations["get-healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminAuthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description Basic admin information */
            admin: components["schemas"]["AdminOutput"];
            /** @description JWT token for authenticated requests */
            token: string;
        };
        AdminOutput: {
            Body: components["schemas"]["AdminOutputBody"];
        };
        AdminOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description Admin's address, optional */
            address?: string;
            /** @description Admin's unique adminname, alphanumeric and underscores only, 3-50 chars */
            adminname: string;
            /** @description Admin's bio or description, optional */
            bio?: string;
            /**
             * Format: date-time
             * @description Creation timestamp of the admin record
             */
            createdAt: string;
            /** @description Unique Email for the admin */
            email: string;
            /** @description First name of the admin, optional */
            firstName?: string;
            /** @description Unique identifier for the admin */
            id: string;
            /** @description URL of the admin's profile image, optional */
            imageUrl?: string;
            /** @description Last name of the admin, optional */
            lastName?: string;
            /** @description Admin's phone number, optional */
            phone?: string;
            /** @description Admin preferences or settings, optional */
            preferences?: {
                [key: string]: unknown;
            };
            /** @description Admin's role, one of 'admin', 'professional', 'admin', 'superadmin' */
            role: string;
            /** @description Admin's social media links, optional */
            socialLinks?: {
                [key: string]: string;
            };
            /**
             * Format: date-time
             * @description Last update timestamp of the admin record
             */
            updatedAt: string;
            /** @description desc:Verification status for different methods, optional */
            verified?: {
                [key: string]: boolean;
            };
        };
        CreateAdminInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description desc:Admin's address, optional */
            address?: string;
            /** @description minLength:3,maxLength:50,pattern:^[a-zA-Z0-9_]+$, desc:Unique adminname, alphanumeric and underscores only, 3-50 chars */
            adminname: string;
            /** @description desc:Admin's bio or description, optional */
            bio?: string;
            /** @description minLength:5,maxLength:100, desc:Admin's email address */
            email: string;
            /** @description desc:Admin's first name, optional */
            firstName?: string;
            /** @description desc:URL of the admin's profile image, optional */
            imageUrl?: string;
            /** @description desc:Admin's last name, optional */
            lastName?: string;
            /** @description minLength:8,maxLength:50, desc:Admin's password (min 8 chars) */
            password: string;
            /** @description desc:Admin's phone number, optional */
            phone?: string;
            /** @description desc:Admin preferences or settings, optional */
            preferences?: {
                [key: string]: unknown;
            };
            /** @description desc:Referral code used by the admin, optional */
            referralCode?: string;
            /** @description desc:Admin ID or email or adminname of the admin who referred this admin, optional */
            referredBy?: string;
            /** @description enum:admin,professional,admin,superadmin, desc:Admin role, one of 'admin', 'superadmin' */
            role?: string;
            /** @description desc:Admin's social media links, optional */
            socialLinks?: {
                [key: string]: string;
            };
        };
        CreateUserInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description desc:User's address, optional */
            address?: string;
            /** @description desc:User's bio or description, optional */
            bio?: string;
            /** @description minLength:5,maxLength:100, desc:User's email address */
            email: string;
            /** @description desc:User's first name, optional */
            firstName?: string;
            /** @description desc:URL of the user's profile image, optional */
            imageUrl?: string;
            /** @description desc:User's last name, optional */
            lastName?: string;
            /** @description minLength:8,maxLength:50, desc:User's password (min 8 chars) */
            password: string;
            /** @description desc:User's phone number, optional */
            phone?: string;
            /** @description desc:User preferences or settings, optional */
            preferences?: {
                [key: string]: unknown;
            };
            /** @description desc:Referral code used by the user, optional */
            referralCode?: string;
            /** @description desc:User ID or email or username of the user who referred this user, optional */
            referredBy?: string;
            /** @description enum:user,professional, desc:User role, one of 'user', 'professional' */
            role?: string;
            /** @description desc:User's social media links, optional */
            socialLinks?: {
                [key: string]: string;
            };
            /** @description minLength:3,maxLength:50,pattern:^[a-zA-Z0-9_]+$, desc:Unique username, alphanumeric and underscores only, 3-50 chars */
            username: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             */
            status?: number;
            /** @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error. */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             */
            type: string;
        };
        GetSortOptionsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            data: string[] | null;
        };
        HealthCheckOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description API health status */
            status: string;
        };
        HealthStatus: {
            database: string;
            /** Format: double */
            load: number;
            server: string;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description User or admin's email address or username */
            identifier: string;
            /** @description User's password -- minLength:8,maxLength:50 */
            password: string;
        };
        LogoutOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description A confirmation message */
            message: string;
        };
        MetadataContact: {
            email: string;
            name: string;
            url: string;
        };
        MetadataLinks: {
            privacyPolicy: string;
            self: string;
        };
        MetadataOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            contact: components["schemas"]["MetadataContact"];
            description: string;
            documentation: string;
            environment: string;
            health: components["schemas"]["HealthStatus"];
            links: components["schemas"]["MetadataLinks"];
            service: string;
            status: string;
            uptime: string;
            version: string;
        };
        PaginatedResponseUserOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            data: components["schemas"]["UserOutputBody"][] | null;
            meta: components["schemas"]["PaginationMeta"];
        };
        PaginationMeta: {
            /** Format: int64 */
            currentPage: number;
            hasNextPage: boolean;
            hasPrevPage: boolean;
            /** Format: int64 */
            itemsPerPage: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int64 */
            totalPages: number;
        };
        ScanOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            results: components["schemas"]["ScanPageOutput"][] | null;
        };
        ScanPageOutput: {
            fileName: string;
            /** Format: int64 */
            pageNumber: number;
            text: string;
        };
        UserAuthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description JWT token for authenticated requests */
            token: string;
            /** @description Basic public user information */
            user: components["schemas"]["UserOutput"];
        };
        UserOutput: {
            Body: components["schemas"]["UserOutputBody"];
        };
        UserOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             */
            readonly $schema?: string;
            /** @description User's address, optional */
            address?: string;
            /** @description User's bio or description, optional */
            bio?: string;
            /**
             * Format: date-time
             * @description Creation timestamp of the user record
             */
            createdAt: string;
            /** @description Unique Email for the user */
            email: string;
            /** @description First name of the user, optional */
            firstName?: string;
            /** @description Unique identifier for the user */
            id: string;
            /** @description URL of the user's profile image, optional */
            imageUrl?: string;
            /** @description Last name of the user, optional */
            lastName?: string;
            /** @description User's phone number, optional */
            phone?: string;
            /** @description User preferences or settings, optional */
            preferences?: {
                [key: string]: unknown;
            };
            /** @description User's role, one of 'user', 'professional' */
            role: string;
            /** @description User's social media links, optional */
            socialLinks?: {
                [key: string]: string;
            };
            /**
             * Format: date-time
             * @description Last update timestamp of the user record
             */
            updatedAt: string;
            /** @description User's unique username, alphanumeric and underscores only, 3-50 chars */
            username: string;
            /** @description desc:Verification status for different methods, optional */
            verified?: {
                [key: string]: boolean;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-create-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-admin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-admin-by-identifier": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer token */
                Authorization?: string;
            };
            path: {
                /**
                 * @description Either the admin's ID, email, or adminname to retrieve the admin information
                 * @example axyut
                 */
                idORmailORadminname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    Domain?: string;
                    Expires?: string;
                    HttpOnly?: boolean;
                    MaxAge?: number;
                    Name?: string;
                    Partitioned?: boolean;
                    Path?: string;
                    Quoted?: boolean;
                    Raw?: string;
                    RawExpires?: string;
                    SameSite?: number;
                    Secure?: boolean;
                    "Set-Cookie"?: string;
                    Unparsed?: string;
                    Value?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-ocr-scan": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    files?: string[];
                    /**
                     * @description Tesseract language code(s) for all files (e.g., 'eng', 'nep', 'eng+hin').
                     * @default nep
                     */
                    lang?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAuthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAuthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-all-users": {
        parameters: {
            query?: {
                /** @description The page number to retrieve. */
                page?: number;
                /** @description The number of items to return per page. */
                limit?: number;
                /** @description Field to sort by. */
                sortBy?: string;
                /** @description Sort order (asc or desc). */
                sortOrder?: "asc" | "desc";
            };
            header?: {
                /** @description Bearer token */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseUserOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user-sort-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSortOptionsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user-by-identifier": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer token */
                Authorization?: string;
            };
            path: {
                /**
                 * @description Either the user's ID, email, or username to retrieve the user information
                 * @example axyut
                 */
                idORmailORusername: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
